const BUSINESS_ERROR_CODES = {
  SLUG_TAKEN: 'SL02',
  ACCESS_CODE_REQUIRED: 'AC01',
  PRIVATE_ACCESS_CODE_REQUIRED: 'AC03',
  INVALID_ACCESS_CODE: 'AC04',
  ACCESS_CODE_PUBLIC_FORBIDDEN: 'AC05',
  NOT_FOUND: 'NF01',
  DRAFT_NOT_FOUND: 'NF02',
};

const SUPPORTED_CURRENCIES = ['NGN', 'USD', 'GBP', 'GHS'];
const CARD_STATUSES = {
  DRAFT: 'draft',
  PUBLISHED: 'published',
};
const ACCESS_TYPES = {
  PUBLIC: 'public',
  PRIVATE: 'private',
};

module.exports = {
  ACCESS_TYPES,
  BUSINESS_ERROR_CODES,
  CARD_STATUSES,
  SUPPORTED_CURRENCIES,
};
